"""
Manual audit of the keyword-based REFUSE/COMPLY classifier.

The classifier in `utils.classify_response` is a 19-phrase regex that's
identical to the one used by the Gemma pipeline. For paper-grade work
on Qwen we need to (a) verify it doesn't systematically misclassify
Qwen-flavored refusals (Qwen3 may have different stock phrasings than
Gemma) and (b) catch any false positives where compliance text happens
to match a refusal phrase.

Usage:
    # Audit a Stage 06 / Stage 08 output JSON
    python3 scripts/pipeline_qwen/audit_classifier.py \\
        --input <run-dir>/06_causal/causal_results.json \\
        --n-sample 50 \\
        --out audits/qwen_stage06_audit.txt

    # Audit a verify_dataset_qwen.py output
    python3 scripts/pipeline_qwen/audit_classifier.py \\
        --input dataset/qwen_dataset_verification.json --n-sample 80

The script samples N records uniformly at random (seeded), prints each
with its current classifier label and `[ ]` for the auditor to mark
agreement / disagreement, and emits a copy-paste-friendly text file the
auditor can edit. After review, run with `--score <reviewed.txt>` to
compute precision/recall and propose phrase additions.

This is offline / CPU-only. No model load.
"""
from __future__ import annotations

import argparse
import json
import random
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from utils import classify_response


def _walk_records(obj):
    """Yield {"context": str, "response": str, "cls": str} from a Stage-output
    JSON, regardless of which stage produced it. Recognises keys used by
    Stage 06 (baseline/interventions), verify_dataset_qwen (bare/ctrl/jb
    arrays), Stage 08 (ablation_results), and 01b_layer_sweep."""
    if isinstance(obj, dict):
        # Stage 06 / 08 nested structure: a record has "response" and "cls"
        if "response" in obj and "cls" in obj:
            yield {
                "context": obj.get("class") or obj.get("cond") or obj.get("prompt") or "",
                "response": obj["response"], "cls": obj["cls"],
            }
        for v in obj.values():
            yield from _walk_records(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _walk_records(v)


def cmd_sample(args):
    with open(args.input) as f:
        data = json.load(f)
    records = list(_walk_records(data))
    if not records:
        print(f"  ❌ no classifier-bearing records found in {args.input}")
        return
    print(f"  Found {len(records)} records.")

    rng = random.Random(args.seed)
    sample = rng.sample(records, min(args.n_sample, len(records)))

    out_lines = []
    out_lines.append(f"# Classifier audit — {args.input}")
    out_lines.append(f"# Sampled {len(sample)} of {len(records)} records "
                     f"(seed {args.seed}).")
    out_lines.append(f"# For each entry, mark `agree=Y` if the regex label is "
                     f"correct, `agree=N` if wrong.")
    out_lines.append(f"# Then run: python3 audit_classifier.py --score {args.out}")
    out_lines.append("")
    for i, r in enumerate(sample):
        regex_cls = classify_response(r["response"])
        # Sanity: regex_cls should match the stored cls (it was generated by
        # the same function). If not, something is inconsistent in the data.
        marker = "" if regex_cls == r["cls"] else "  [!! stored vs regex mismatch !!]"
        out_lines.extend([
            f"## Record {i+1}/{len(sample)}{marker}",
            f"context: {r['context']}",
            f"regex_cls: {regex_cls}",
            f"agree: ?      # change to Y or N",
            f"response: {r['response']}",
            "",
        ])

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out_lines))
    print(f"  Wrote {out_path}")
    print(f"  Now: review the file, set agree=Y or agree=N for each record,")
    print(f"  then run: python3 audit_classifier.py --score {out_path}")


def cmd_score(args):
    text = Path(args.score).read_text()

    # Parse each ## Record block
    pattern = re.compile(
        r"## Record (\d+)/(\d+).*?\nregex_cls: (\w+)\nagree: ([YN?]).*?\nresponse: (.+?)(?=\n##|\Z)",
        re.DOTALL,
    )
    results = []
    for m in pattern.finditer(text):
        idx, total, regex_cls, agree, resp = m.groups()
        results.append({
            "idx": int(idx), "regex_cls": regex_cls, "agree": agree,
            "response": resp.strip(),
        })

    if not results:
        print("  ❌ couldn't parse any records — is this a sample file?")
        return

    n = len(results)
    n_unreviewed = sum(1 for r in results if r["agree"] == "?")
    if n_unreviewed:
        print(f"  ⚠️ {n_unreviewed}/{n} records still marked agree=?")

    # Confusion matrix
    tp = fp = tn = fn = 0
    disagreements = []
    for r in results:
        if r["agree"] == "?":
            continue
        regex_says_refuse = r["regex_cls"] == "REFUSE"
        actually_refuses = (regex_says_refuse) if r["agree"] == "Y" else (not regex_says_refuse)
        if actually_refuses and regex_says_refuse:
            tp += 1
        elif actually_refuses and not regex_says_refuse:
            fn += 1
            disagreements.append(r)
        elif not actually_refuses and regex_says_refuse:
            fp += 1
            disagreements.append(r)
        else:
            tn += 1

    n_reviewed = tp + fp + tn + fn
    if n_reviewed == 0:
        print(f"  No reviewed records yet (all marked agree=?)")
        return

    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    accuracy = (tp + tn) / n_reviewed
    print(f"\n  Reviewed: {n_reviewed}/{n}")
    print(f"  Confusion (treating REFUSE as positive class):")
    print(f"    TP={tp}  FP={fp}  TN={tn}  FN={fn}")
    print(f"    accuracy : {accuracy:.1%}")
    print(f"    precision: {precision:.1%}  (of regex REFUSE, {precision:.1%} are real)")
    print(f"    recall   : {recall:.1%}  (of real REFUSE, {recall:.1%} caught)")

    if disagreements:
        print(f"\n  {len(disagreements)} disagreement(s) — first 10 responses:")
        for r in disagreements[:10]:
            verdict = "false-positive" if r["agree"] == "N" and r["regex_cls"] == "REFUSE" else "false-negative"
            print(f"    [{verdict}] regex={r['regex_cls']}: {r['response'][:140]}")
        print(f"\n  → If false-negatives recur with a common phrase, add it to "
              f"utils.classify_response and re-run BOTH Gemma + Qwen pipelines "
              f"so the comparison stays symmetric.")


def main():
    p = argparse.ArgumentParser(description="Audit utils.classify_response")
    sub = p.add_subparsers(dest="cmd")

    g = p.add_argument_group("modes (mutually exclusive)")
    g.add_argument("--input", type=Path, help="Input JSON to sample from")
    g.add_argument("--score", type=Path, help="Reviewed audit file to score")

    p.add_argument("--n-sample", type=int, default=50)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--out", type=Path,
                   default=Path("audits/classifier_audit.txt"))
    args = p.parse_args()

    if args.input and args.score:
        p.error("pass --input OR --score, not both")
    if args.input:
        cmd_sample(args)
    elif args.score:
        cmd_score(args)
    else:
        p.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
