# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: rbinsafi@gmail.com
full_name: Ruqiya
license: MIT
min_python_version: '3.10'
org: AutoInterp
project_name: Refusa- Lens
project_short_description: Refusal-Lens is a package for analyzing refusal behavior.
python_name: refusal_lens
typing: strict
url: https://github.com/AutoInterp/Refusal-Lens
